# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ukhirani/Umang/Projects/Active/simple-synth

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ukhirani/Umang/Projects/Active/simple-synth

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ukhirani/Umang/Projects/Active/simple-synth/CMakeFiles /home/ukhirani/Umang/Projects/Active/simple-synth//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ukhirani/Umang/Projects/Active/simple-synth/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/ukhirani/Umang/Projects/Active/simple-synth/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SimpleSynth

# Build rule for target.
SimpleSynth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleSynth
.PHONY : SimpleSynth

# fast build rule for target.
SimpleSynth/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/build
.PHONY : SimpleSynth/fast

#=============================================================================
# Target rules for targets named SimpleSynth_All

# Build rule for target.
SimpleSynth_All: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleSynth_All
.PHONY : SimpleSynth_All

# fast build rule for target.
SimpleSynth_All/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_All.dir/build.make CMakeFiles/SimpleSynth_All.dir/build
.PHONY : SimpleSynth_All/fast

#=============================================================================
# Target rules for targets named SimpleSynth_Standalone

# Build rule for target.
SimpleSynth_Standalone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleSynth_Standalone
.PHONY : SimpleSynth_Standalone

# fast build rule for target.
SimpleSynth_Standalone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/build
.PHONY : SimpleSynth_Standalone/fast

#=============================================================================
# Target rules for targets named SimpleSynth_rc_lib

# Build rule for target.
SimpleSynth_rc_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleSynth_rc_lib
.PHONY : SimpleSynth_rc_lib

# fast build rule for target.
SimpleSynth_rc_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_rc_lib.dir/build.make CMakeFiles/SimpleSynth_rc_lib.dir/build
.PHONY : SimpleSynth_rc_lib/fast

#=============================================================================
# Target rules for targets named SimpleSynth_VST3

# Build rule for target.
SimpleSynth_VST3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleSynth_VST3
.PHONY : SimpleSynth_VST3

# fast build rule for target.
SimpleSynth_VST3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/build
.PHONY : SimpleSynth_VST3/fast

#=============================================================================
# Target rules for targets named juce_vst3_helper

# Build rule for target.
juce_vst3_helper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 juce_vst3_helper
.PHONY : juce_vst3_helper

# fast build rule for target.
juce_vst3_helper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/build
.PHONY : juce_vst3_helper/fast

MaximilianDSP/maximilian.obj: MaximilianDSP/maximilian.cpp.obj
.PHONY : MaximilianDSP/maximilian.obj

# target to build an object file
MaximilianDSP/maximilian.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/MaximilianDSP/maximilian.cpp.obj
.PHONY : MaximilianDSP/maximilian.cpp.obj

MaximilianDSP/maximilian.i: MaximilianDSP/maximilian.cpp.i
.PHONY : MaximilianDSP/maximilian.i

# target to preprocess a source file
MaximilianDSP/maximilian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/MaximilianDSP/maximilian.cpp.i
.PHONY : MaximilianDSP/maximilian.cpp.i

MaximilianDSP/maximilian.s: MaximilianDSP/maximilian.cpp.s
.PHONY : MaximilianDSP/maximilian.s

# target to generate assembly for a file
MaximilianDSP/maximilian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/MaximilianDSP/maximilian.cpp.s
.PHONY : MaximilianDSP/maximilian.cpp.s

SimpleSynth_artefacts/JuceLibraryCode/SimpleSynth_resources.res: SimpleSynth_artefacts/JuceLibraryCode/SimpleSynth_resources.rc.res
.PHONY : SimpleSynth_artefacts/JuceLibraryCode/SimpleSynth_resources.res

# target to build an object file
SimpleSynth_artefacts/JuceLibraryCode/SimpleSynth_resources.rc.res:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_rc_lib.dir/build.make CMakeFiles/SimpleSynth_rc_lib.dir/SimpleSynth_artefacts/JuceLibraryCode/SimpleSynth_resources.rc.res
.PHONY : SimpleSynth_artefacts/JuceLibraryCode/SimpleSynth_resources.rc.res

Source/Chorus.obj: Source/Chorus.cpp.obj
.PHONY : Source/Chorus.obj

# target to build an object file
Source/Chorus.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Chorus.cpp.obj
.PHONY : Source/Chorus.cpp.obj

Source/Chorus.i: Source/Chorus.cpp.i
.PHONY : Source/Chorus.i

# target to preprocess a source file
Source/Chorus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Chorus.cpp.i
.PHONY : Source/Chorus.cpp.i

Source/Chorus.s: Source/Chorus.cpp.s
.PHONY : Source/Chorus.s

# target to generate assembly for a file
Source/Chorus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Chorus.cpp.s
.PHONY : Source/Chorus.cpp.s

Source/Crunch.obj: Source/Crunch.cpp.obj
.PHONY : Source/Crunch.obj

# target to build an object file
Source/Crunch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Crunch.cpp.obj
.PHONY : Source/Crunch.cpp.obj

Source/Crunch.i: Source/Crunch.cpp.i
.PHONY : Source/Crunch.i

# target to preprocess a source file
Source/Crunch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Crunch.cpp.i
.PHONY : Source/Crunch.cpp.i

Source/Crunch.s: Source/Crunch.cpp.s
.PHONY : Source/Crunch.s

# target to generate assembly for a file
Source/Crunch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Crunch.cpp.s
.PHONY : Source/Crunch.cpp.s

Source/Envelope.obj: Source/Envelope.cpp.obj
.PHONY : Source/Envelope.obj

# target to build an object file
Source/Envelope.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Envelope.cpp.obj
.PHONY : Source/Envelope.cpp.obj

Source/Envelope.i: Source/Envelope.cpp.i
.PHONY : Source/Envelope.i

# target to preprocess a source file
Source/Envelope.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Envelope.cpp.i
.PHONY : Source/Envelope.cpp.i

Source/Envelope.s: Source/Envelope.cpp.s
.PHONY : Source/Envelope.s

# target to generate assembly for a file
Source/Envelope.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Envelope.cpp.s
.PHONY : Source/Envelope.cpp.s

Source/Filter.obj: Source/Filter.cpp.obj
.PHONY : Source/Filter.obj

# target to build an object file
Source/Filter.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Filter.cpp.obj
.PHONY : Source/Filter.cpp.obj

Source/Filter.i: Source/Filter.cpp.i
.PHONY : Source/Filter.i

# target to preprocess a source file
Source/Filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Filter.cpp.i
.PHONY : Source/Filter.cpp.i

Source/Filter.s: Source/Filter.cpp.s
.PHONY : Source/Filter.s

# target to generate assembly for a file
Source/Filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Filter.cpp.s
.PHONY : Source/Filter.cpp.s

Source/Limiter.obj: Source/Limiter.cpp.obj
.PHONY : Source/Limiter.obj

# target to build an object file
Source/Limiter.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Limiter.cpp.obj
.PHONY : Source/Limiter.cpp.obj

Source/Limiter.i: Source/Limiter.cpp.i
.PHONY : Source/Limiter.i

# target to preprocess a source file
Source/Limiter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Limiter.cpp.i
.PHONY : Source/Limiter.cpp.i

Source/Limiter.s: Source/Limiter.cpp.s
.PHONY : Source/Limiter.s

# target to generate assembly for a file
Source/Limiter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Limiter.cpp.s
.PHONY : Source/Limiter.cpp.s

Source/Oscillator.obj: Source/Oscillator.cpp.obj
.PHONY : Source/Oscillator.obj

# target to build an object file
Source/Oscillator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Oscillator.cpp.obj
.PHONY : Source/Oscillator.cpp.obj

Source/Oscillator.i: Source/Oscillator.cpp.i
.PHONY : Source/Oscillator.i

# target to preprocess a source file
Source/Oscillator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Oscillator.cpp.i
.PHONY : Source/Oscillator.cpp.i

Source/Oscillator.s: Source/Oscillator.cpp.s
.PHONY : Source/Oscillator.s

# target to generate assembly for a file
Source/Oscillator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/Oscillator.cpp.s
.PHONY : Source/Oscillator.cpp.s

Source/PluginEditor.obj: Source/PluginEditor.cpp.obj
.PHONY : Source/PluginEditor.obj

# target to build an object file
Source/PluginEditor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/PluginEditor.cpp.obj
.PHONY : Source/PluginEditor.cpp.obj

Source/PluginEditor.i: Source/PluginEditor.cpp.i
.PHONY : Source/PluginEditor.i

# target to preprocess a source file
Source/PluginEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/PluginEditor.cpp.i
.PHONY : Source/PluginEditor.cpp.i

Source/PluginEditor.s: Source/PluginEditor.cpp.s
.PHONY : Source/PluginEditor.s

# target to generate assembly for a file
Source/PluginEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/PluginEditor.cpp.s
.PHONY : Source/PluginEditor.cpp.s

Source/PluginProcessor.obj: Source/PluginProcessor.cpp.obj
.PHONY : Source/PluginProcessor.obj

# target to build an object file
Source/PluginProcessor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/PluginProcessor.cpp.obj
.PHONY : Source/PluginProcessor.cpp.obj

Source/PluginProcessor.i: Source/PluginProcessor.cpp.i
.PHONY : Source/PluginProcessor.i

# target to preprocess a source file
Source/PluginProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/PluginProcessor.cpp.i
.PHONY : Source/PluginProcessor.cpp.i

Source/PluginProcessor.s: Source/PluginProcessor.cpp.s
.PHONY : Source/PluginProcessor.s

# target to generate assembly for a file
Source/PluginProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/PluginProcessor.cpp.s
.PHONY : Source/PluginProcessor.cpp.s

Source/ReverbComponent.obj: Source/ReverbComponent.cpp.obj
.PHONY : Source/ReverbComponent.obj

# target to build an object file
Source/ReverbComponent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/ReverbComponent.cpp.obj
.PHONY : Source/ReverbComponent.cpp.obj

Source/ReverbComponent.i: Source/ReverbComponent.cpp.i
.PHONY : Source/ReverbComponent.i

# target to preprocess a source file
Source/ReverbComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/ReverbComponent.cpp.i
.PHONY : Source/ReverbComponent.cpp.i

Source/ReverbComponent.s: Source/ReverbComponent.cpp.s
.PHONY : Source/ReverbComponent.s

# target to generate assembly for a file
Source/ReverbComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/Source/ReverbComponent.cpp.s
.PHONY : Source/ReverbComponent.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_Standalone.dir/build.make CMakeFiles/SimpleSynth_Standalone.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth_VST3.dir/build.make CMakeFiles/SimpleSynth_VST3.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.s

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.obj: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.obj

# target to build an object file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.obj
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.obj

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.i: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.i

# target to preprocess a source file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.i
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.i

home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.s: home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.s

# target to generate assembly for a file
home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleSynth.dir/build.make CMakeFiles/SimpleSynth.dir/home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.s
.PHONY : home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SimpleSynth_All"
	@echo "... SimpleSynth"
	@echo "... SimpleSynth_Standalone"
	@echo "... SimpleSynth_VST3"
	@echo "... SimpleSynth_rc_lib"
	@echo "... juce_vst3_helper"
	@echo "... MaximilianDSP/maximilian.obj"
	@echo "... MaximilianDSP/maximilian.i"
	@echo "... MaximilianDSP/maximilian.s"
	@echo "... SimpleSynth_artefacts/JuceLibraryCode/SimpleSynth_resources.res"
	@echo "... Source/Chorus.obj"
	@echo "... Source/Chorus.i"
	@echo "... Source/Chorus.s"
	@echo "... Source/Crunch.obj"
	@echo "... Source/Crunch.i"
	@echo "... Source/Crunch.s"
	@echo "... Source/Envelope.obj"
	@echo "... Source/Envelope.i"
	@echo "... Source/Envelope.s"
	@echo "... Source/Filter.obj"
	@echo "... Source/Filter.i"
	@echo "... Source/Filter.s"
	@echo "... Source/Limiter.obj"
	@echo "... Source/Limiter.i"
	@echo "... Source/Limiter.s"
	@echo "... Source/Oscillator.obj"
	@echo "... Source/Oscillator.i"
	@echo "... Source/Oscillator.s"
	@echo "... Source/PluginEditor.obj"
	@echo "... Source/PluginEditor.i"
	@echo "... Source/PluginEditor.s"
	@echo "... Source/PluginProcessor.obj"
	@echo "... Source/PluginProcessor.i"
	@echo "... Source/PluginProcessor.s"
	@echo "... Source/ReverbComponent.obj"
	@echo "... Source/ReverbComponent.i"
	@echo "... Source/ReverbComponent.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_basics/juce_audio_basics.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_devices/juce_audio_devices.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_formats/juce_audio_formats.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_audio_utils/juce_audio_utils.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_core/juce_core_CompilationTime.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_data_structures/juce_data_structures.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_dsp/juce_dsp.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_events/juce_events.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_basics/juce_gui_basics.s"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.obj"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.i"
	@echo "... home/ukhirani/Umang/SDKs_and_Paths/juce-8.0.8-linux/JUCE/modules/juce_gui_extra/juce_gui_extra.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/ukhirani/Umang/Projects/Active/simple-synth/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

